### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by tobstarr** [benbjohnson/ego#15]
Is there a recommended way to make sure all people working on a project using ego use the same version of ego? Different versions of ego can lead to unnecessary overwrites of the generated ego.go file without changes to the source templates.

**Comment by tobstarr** [comment]
If this is bothering anybody else: we solved it for us by copying cmd/ego/main.go to our project (into /tools/custom-ego/main.go) and so it is picked up by godep (and the actual ego code is vendored). We no longer use the ego CLI tool but just `go run tools/custom-ego/main.go ...` in our build process then.

**Comment by benbjohnson** [comment]
Sorry for the delay. I added a v0.1.0 release and pushed pre-build binaries to GitHub:

https://github.com/benbjohnson/ego/releases/tag/v0.1.0
