### ISSUE TITLE
undefined: User

### ISSUE THREAD

**Issue by vadimyer** [benbjohnson/ego#18]
Running your example, I get undefined: User 
What could be a problem? Thanks.

**Comment by benbjohnson** [comment]
It's likely that you referenced `User` in your template but your template is not in the same package as `User`. Can you post the error and your template?

**Comment by vadimyer** [comment]
I've created a template file (copied from your example) in mypkg/example.ego
Then ran ego mypkg, and the file ego.go appeared in the directory where I'm running it:
```
// Generated by ego.
// DO NOT EDIT

package root
import (
"fmt"
"html"
"io"
"strings"
)
//line mypkg/example.ego:1
 func MyTmpl(w io.Writer, u *User) error  {
//line mypkg/example.ego:2
_, _ = fmt.Fprint(w, "\n\n")
//line mypkg/example.ego:4
_, _ = fmt.Fprint(w, "\n\n<html>\n  <body>\n    <h1>Hello ")
//line mypkg/example.ego:7
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  strings.TrimSpace(u.FirstName) )))
//line mypkg/example.ego:7
_, _ = fmt.Fprint(w, "!</h1>\n\n    <p>Here's a list of your favorite colors:</p>\n    <ul>\n      ")
//line mypkg/example.ego:11
 for _, colorName := range u.FavoriteColors {
//line mypkg/example.ego:12
_, _ = fmt.Fprint(w, "\n        <li>")
//line mypkg/example.ego:12
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  colorName )))
//line mypkg/example.ego:12
_, _ = fmt.Fprint(w, "</li>\n      ")
//line mypkg/example.ego:13
 }
//line mypkg/example.ego:14
_, _ = fmt.Fprint(w, "\n    </ul>\n  </body>\n</html>\n")
return nil
}
```

I then moved the ego.go into mypkg directory, and imported "../root/mypkg" in my main file. And got this error:
```mypkg/example.ego:1[/root/mypkg/ego.go:12]: undefined: User```

Sorry new to this packaging system... Just wanna try your approach.

**Comment by benbjohnson** [comment]
@vadimyer ah, ok. the `User` is just an example of a type that you might have in your package. The example in the README is not meant to be a full working example -- just a quick sample of usage. An `example` subpackage in the ego repo is probably a good idea.
