### ISSUE TITLE
(perf) Replace bytes.Buffer with strings.Builder

### ISSUE THREAD

**Issue by astec** [benbjohnson/ego#32]
Improve performance by using `strings.Builder` instead of `bytes.Buffer` where possible.

https://golang.org/doc/go1.10#strings

https://golang.org/pkg/strings/#Builder

**Comment by benbjohnson** [comment]
@astec Are you having performance issues? I find the codegen pretty fast and I'm not sure breaking 1.9 compatibility is worth it.

**Comment by astec** [comment]
No, I don't have performance issues and probably you are right so am closing the issue.
