### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fabianfreyer** [benbjohnson/ego#34]
Would it be possible to tag the current master version as 0.3.0?

I'm currently working on creating a FreeBSD port for [faktory]. This uses the current master ego for its webui. To keep things clean, I'm also [writing a FreeBSD port for ego](https://reviews.freebsd.org/D16408). As the templates used by faktory aren't compatible with ego 0.2.0, it'd be great to be able to package a new release of ego.

[faktory]: https://github.com/contribsys/faktory

**Comment by benbjohnson** [comment]
np. I tagged c3b6a2e7bcef0497c9c0149e8d112762639e8949 as `v0.3.0`. 👍

**Comment by fabianfreyer** [comment]
Thanks!
