### ISSUE TITLE
README: go get updates go mod in go1.16

### ISSUE THREAD

**Issue by peebs** [benbjohnson/ego#37]
From the README executing `go get github.com/benbjohnson/ego/...` will just update go.mod and go.sum if executed from inside the project directory with go 1.16. I believe this is because GO111MODULE is now set to on by default.

`go install github.com/benbjohnson/ego@latest` will work from any directory, but only in go 1.16. The wtf dial project relies on go1.16 which is why I installed ego and used this alternative command.

**Comment by benbjohnson** [comment]
Thanks for reporting the issue. I updated the README. I also added a release build for Linux. I tried to add one for Mac OS but my laptop didn't like it since it wasn't signed.
