### ISSUE TITLE
v0.4.2 removes necessary whitespace

### ISSUE THREAD

**Issue by mperham** [benbjohnson/ego#40]
My HTML pages are breaking because the v0.4.2 release strips the whitespace between these ego tags:

```
<header class="row">
  <div class="col-5">
    <h3><%= t(req, "Batch") %> <%= st.Bid %></h3>
  </div>
</header>
```

The generated `<h3>` should contain `Batch abc123` but contains `Batchabc123`. v0.4.1 works fine.

**Comment by benbjohnson** [comment]
Ah, sorry about that Mike. I reverted the commits and released `v0.4.3` (which should be basically the same as `v0.4.1`). Thanks for reporting the issue!

https://github.com/benbjohnson/ego/releases/tag/v0.4.3
